# -*- coding: utf-8 -*-
"""La_Peter_CV_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16xl8U7AlA4qi1zEuPnm_JEoJlLrIk_2q
"""

!apt-get update
!apt-get install -y tesseract-ocr
!apt-get install -y tesseract-ocr-vie
!pip install pytesseract pillow

import pytesseract
from PIL import Image
import matplotlib.pyplot as plt
#pytesseract.pytesseract.tesseract_cmd = r"C:\Program Files\Tesseract-OCR\tesseract.exe"
def process_an_image(image_path):
        image = Image.open(image_path)
        text = pytesseract.image_to_string(image, lang="vie")
        fig, axes = plt.subplots(1, 2, figsize=(12, 5))
        axes[0].imshow(image)
        axes[0].axis("off")
        axes[0].set_title("Original Image")
        axes[1].text(0, 1, text, fontsize=12, verticalalignment='top', wrap=True)
        axes[1].axis("off")
        axes[1].set_title("OCR Output")
        plt.show()

process_an_image('/content/cv_data/vtest1.png')

process_an_image('/content/cv_data/vtest2.jpg')

process_an_image('/content/cv_data/vtest3.jpg')

process_an_image('/content/cv_data/vtest4.png')

process_an_image('/content/cv_data/vtest5.png')

process_an_image('/content/cv_data/menu1.jpg')

process_an_image('/content/cv_data/menu2.png')

process_an_image('/content/cv_data/menu3.jpg')